package dao;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class DBConnection {

    private static final String URL = "jdbc:hsqldb:file:chatbotdb";
    private static final String USER = "SA";
    private static final String PASSWORD = "";

    // Kết nối database
    public static Connection getConnection() throws SQLException {
        return DriverManager.getConnection(URL, USER, PASSWORD);
    }

    // ĐỔI TÊN HÀM TỪ 'createTables' THÀNH 'initTables' Ở ĐÂY:
    public static void initTables() {
        try (Connection conn = getConnection();
             Statement stmt = conn.createStatement()) {

            // Tạo bảng USERS
            String sqlUsers = """
                CREATE TABLE IF NOT EXISTS USERS (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    username VARCHAR(50) UNIQUE NOT NULL,
                    password_hash VARCHAR(255) NOT NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
            """;
            stmt.executeUpdate(sqlUsers);

            // Tạo bảng MESSAGES
            String sqlMessages = """
                CREATE TABLE IF NOT EXISTS MESSAGES (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id INTEGER NOT NULL,
                    role VARCHAR(10) NOT NULL,
                    content VARCHAR(4000),
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (user_id) REFERENCES USERS(id)
                )
            """;
            stmt.executeUpdate(sqlMessages);

            System.out.println("Đã khởi tạo các bảng USERS và MESSAGES!");

        } catch (SQLException e) {
            System.err.println("Lỗi khởi tạo bảng: " + e.getMessage());
            e.printStackTrace();
        }
    }
}